config/routes.rb
Rails.application.routes.draw do

  root 'workouts#new'
  get 'workouts' => 'workouts#index'

  get 'workouts/new'

  get 'workouts/create'

  get 'workouts/edit'

  get 'workouts/update'

  get 'workouts/destroy'

  post 'workouts' => 'workouts#create'

  devise_for :users

end

app/models/age_division.rb
class AgeDivision < ActiveRecord::Base

has_many :athletes

end

app/models/athlete.rb
class Athlete < ActiveRecord::Base
  has_many :attempts
  has_many :lifts, through: :attempts

  belongs_to :competition_class
  belongs_to :weight_class
  belongs_to :age_division
  belongs_to :equipment_division


  def squat_max
    @athlete.attempts.find_all {|x|  x.lift.name == "Squat"}.max_by {|s| s.weight}.weight
  end

  def deadlift_max
    @athlete.attempts.find_all {|x|  x.lift.name == "Deadlift"}.max_by {|s| s.weight}.weight
  end

  def bench_max
    @athlete.attempts.find_all {|x|  x.lift.name == "Bench Press"}.max_by {|s| s.weight}.weight
  end

  def total
    @total = squat_max + deadlift_max + bench_max
  end


end

app/models/attempt.rb
class Attempt < ActiveRecord::Base
  belongs_to :athlete
  belongs_to :lift
end

app/models/competition_class.rb
class CompetitionClass < ActiveRecord::Base
  
has_many :athletes

end

app/models/equipment_division.rb
class EquipmentDivision < ActiveRecord::Base
  has_many :athletes
end

app/models/lift.rb
class Lift < ActiveRecord::Base
  has_many :attempts
  has_many :athletes, through: :attempts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/weight_class.rb
class WeightClass < ActiveRecord::Base

has_many :athletes

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  
  def index
    @athletes = Athlete.all
  end

  def new
    @athlete = Athlete.new
  end

  def create
    @athlete = Athlete.create(athlete_params)
      respond_to do |format|
      if @athlete.save
        format.html { redirect_to @athlete, notice: 'athlete was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  

  private


  def set_athlete
    @lift = Lift.find(params[:id])
  end

  def athlete_params
    params.require(:athlete).permit(:name, :bwt, :gender, :total, :wilks, :weight_class_id, :competition_class_id, :age_division_id, :equipment_division_id)
  end


end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
  
  def index
    @attempts = Attempt.all
  end

  def new
    @attempt = Attempt.new
  end

  def create
    @attempt = Attempt.create(attempt_params)
      respond_to do |format|
      if @attempt.save
        format.html { redirect_to @attempt, notice: 'attempt was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private


  def set_attempt
    @attempt = Attempt.find(params[:id])
  end

  def attempt_params
    params.require(:attempt).permit(:weight, :athlete_id, :lift_id)
  end

end

app/controllers/lifts_controller.rb
class LiftsController < ApplicationController
  
  def index
  end

  def new
    @lift = Lift.new
  end

  def create
    @lift = Lift.create(lift_params)
      respond_to do |format|
      if @lift.save
        format.html { redirect_to @lift, notice: 'lift was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private


  def set_lift
    @lift = Lift.find(params[:id])
  end

  def lift_params
    params.require(:lift).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<link href='http://fonts.googleapis.com/css?family=Black+Ops+One|Play:400,700' rel='stylesheet' type='text/css'>
  <title>Calcu-Plate</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

</head>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <a class="navbar-brand navbar" href=<%= workouts_new_path%>>CalcuPlate</a>
    </div>
     <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav" >
    <% if user_signed_in? && (current_page?(root_path) || current_page?(workouts_new_path))%>
        <li><a href=<%=workouts_path%> >Your Logs</a></li>
         <li><a href=<%=destroy_user_session_path%> data-method = 'delete'>Sign Out</a></li>

        <% elsif user_signed_in? && current_page?(workouts_path)%>
         <li><a href=<%=destroy_user_session_path%> data-method = "delete">Sign Out</a></li>
         
         <% elsif !user_signed_in? && (current_page?(root_path) || current_page?(workouts_new_path)) %>
              <li><a href=<%=new_user_session_path%>>Sign In</a></li>
              <li><a href=<%=new_user_registration_path%>>Sign Up</a></li>

         <%end%>

      </ul>
    </div>
</div>
</nav>
<body>

  

<%= yield %>

</body>
</html>

app/views/logs/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Calculations</title>
  <link rel="stylesheet" href="css/style.css">
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

</head>


<body>
    
  <div id="wrapper">
    
    <center><h1>Plate Calculator</h1>
    <h4>Because You Don't Even Math, Bro</h4></center>

 <center>  <button class = "weights" id ="plate" value=45><img src = '/assets/45.png'/></button>
      <button class = "weights" id ="threeFive" value=35> <img src = "/assets/35.png"/> </button>
      <button class = "weights" id = "quarter" value = 25> <img src = '/assets/25.png'/> </button>
      <button class = "weights" id = "dime" value = 10> <img src = '/assets/10.png'/> </button>
      <button class = "weights" id = "nickel" value = 5> <img src = '/assets/5.png'/> </button>
       <button class = "weights" id = "two" value = 2.5> <img src = '/assets/2.png'/> </button>
<br/>
<br/>
<br/><br/><br/>
<div id = 'container'>
<div id= "bar"><img src = "/assets/barbell2.png"/></div>

<div id = "first">
  <div id = "firstplates">
    <div id = "r45"></div>
    <div id = "l45"></div>
</div>

  <div id = "first35">
    <div id = "r35"></div>
    <div id = "l35"></div>
</div>

<div id = "first25">
    <div id = "r25"></div>
    <div id = "l25"></div>
</div>

<div id = "first10">
    <div id = "r10"></div>
    <div id = "l10"></div>
</div>

<div id = "first5">
    <div id = "r5"></div>
    <div id = "l5"></div>
</div>

<div id = "first2">
    <div id = "r2"></div>
    <div id = "l2"></div>
</div>

</div>

<div id = "second">
  <div id = "secondplates">
    <div id = "r45b"></div>
    <div id = "l45b"></div>
  </div>

  <div id = "second35">
    <div id = "r35b"></div>
    <div id = "l35b"></div>
  </div>

  <div id = "second25">
    <div id = "r25b"></div>
    <div id = "l25b"></div>
  </div>

  <div id = "second10">
      <div id = "r10b"></div>
      <div id = "l10b"></div>
  </div>

  <div id = "second5">
      <div id = "r5b"></div>
      <div id = "l5b"></div>
  </div>

  <div id = "second2">
    <div id = "r2b"></div>
    <div id = "l2b"></div>
</div>
</div>

<div id = "third">
  <div id = "thirdplates">
    <div id = "r45c"></div>
    <div id = "l45c"></div>
  </div>

  <div id = "third35">
    <div id = "r35c"></div>
    <div id = "l35c"></div>
  </div>

  <div id = "third25">
    <div id = "r25c"></div>
    <div id = "l25c"></div>
  </div>

  <div id = "third10">
    <div id = "r10c"></div>
    <div id = "l10c"></div>
</div>

  <div id = "third5">
      <div id = "r5c"></div>
      <div id = "l5c"></div>
  </div>

  <div id = "third2">
    <div id = "r2c"></div>
    <div id = "l2c"></div>
</div>

</div>

<div id = "fourth">
    <div id = "fourthplates">
    <div id = "r45d"></div>
    <div id = "l45d"></div>
  </div>


  <div id = "fourth35">
    <div id = "r35d"></div>
    <div id = "l35d"></div>
  </div>

  <div id = "fourth25">
    <div id = "r25d"></div>
    <div id = "l25d"></div>
  </div>

<div id = "fourth10">
    <div id = "r10d"></div>
    <div id = "l10d"></div>
</div>

  <div id = "fourth5">
      <div id = "r5d"></div>
      <div id = "l5d"></div>
  </div>

  <div id = "fourth2">
    <div id = "r2d"></div>
    <div id = "l2d"></div>
</div>
</div>

</div>

      <br/>
      <br/>
      <br/>

      <input id = "total"></input>

      <button id = "load">Load</button>
      <button id = "deload">Deload</button>

      <button id = "log">Log</button>

</div>
  

    
</body>
</html>

app/views/workouts/_form.html.erb
<%= form_for @workout, :html => {:multipart => true} do |f| %>
  <% if @workout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
      <% @workout.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

        <%=f.label :weight%>
     <input type="text" id="workout_weight" name="workout[weight]"
       value="<%= @workout.weight %>" /> 
 <button type = "button" id = "load" class="btn btn-primary">Load</button>
<br/>
  
      <br/>
  <% if user_signed_in? %>

<%= f.label :reps %>
<%= f.text_field :reps %>
<br/>
<br/>

 <%= f.label :exercise_id %>

 <%= f.select :exercise_id, options_for_select(@exercises.map{ |s| [s.name, s.id] })  %>
<br/>
<br/>
 <%= f.label "Workout Date" %>
<%= f.date_select :woDate %> 

<br/>
<br/>
      <button id = "log" class="btn btn-success">Log</button>

<%else%>
<%= link_to 'Log In To Log It!', new_user_session_path %> or <%= link_to 'Sign Up', new_user_registration_path%>
<%end%>
<% end %>

app/views/workouts/create.html.erb
<h1>Logs#create</h1>
<p>Find me in app/views/logs/create.html.erb</p>

app/views/workouts/destroy.html.erb
<h1>Logs#destroy</h1>
<p>Find me in app/views/logs/destroy.html.erb</p>

app/views/workouts/edit.html.erb
<h1>Logs#edit</h1>
<p>Find me in app/views/logs/edit.html.erb</p>

app/views/workouts/index.html.erb
<!DOCTYPE html>
<html>
<head>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50626295-1', 'calcu-plate.herokuapp.com');
  ga('send', 'pageview');

</script>
</head>


<body>
<% if @workouts.empty? %>
<center><h3>You don't have any logged workouts!</h3> <br/>
<%= link_to "Start Logging", workouts_new_path %></center>
<%end%>


<center>
<p>Click a date to view your log for that day</p>

<% @workouts.each do |date, wo| %>
<button type="button" class="btn btn-danger btn-lg" data-toggle="collapse" data-target="#a<%=date.gsub(/\W/,'')%>">
<%= date %></button> <br/><br/>

<div id="a<%=date.gsub(/\W/,'')%>" class="collapse">
 <% wo.group_by {|w| w.exercise_id}.each do |exercise, workout|%>
        <h3><%= Exercise.find(exercise).name %></h3>

        <%workout.each do |f|%>
      <p>  <%= f.reps%> x <%= f.weight%></p>
    </br></br>
    <%end%>
    <%end%>
</div>


 <%end%>
    

</center>



</body>

</html>

app/views/workouts/new.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="stylesheets/style.css">
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50626295-1', 'calcu-plate.herokuapp.com');
  ga('send', 'pageview');

</script>

</head>

<body>


  <div id="wrapper">
    
    <center><h1>CALCUPLATE</h1>
    <h4>Because You Don't Even Math, Bro</h4>
    <p>(Click on the weights or enter a number in the text box to load up the bar)</p></center><br/>

 <center>  <button class = "weights" id ="plate" value=45><img src = '/assets/45.png'/></button>
      <button class = "weights" id ="threeFive" value=35> <img src = "/assets/35.png"/> </button>
      <button class = "weights" id = "quarter" value = 25> <img src = '/assets/25.png'/> </button>
      <button class = "weights" id = "dime" value = 10> <img src = '/assets/10.png'/> </button>
      <button class = "weights" id = "nickel" value = 5> <img src = '/assets/5.png'/> </button>
       <button class = "weights" id = "two" value = 2.5> <img src = '/assets/2.png'/> </button>
<br/>
<br/>
<br/><br/><br/>
<div id = 'container'>
<div id= "bar"><img src = "/assets/barbell2.png"/></div>

<div id = "first">
  <div id = "firstplates">
    <div id = "r45"></div>
    <div id = "l45"></div>
</div>

  <div id = "first35">
    <div id = "r35"></div>
    <div id = "l35"></div>
</div>

<div id = "first25">
    <div id = "r25"></div>
    <div id = "l25"></div>
</div>

<div id = "first10">
    <div id = "r10"></div>
    <div id = "l10"></div>
</div>

<div id = "first5">
    <div id = "r5"></div>
    <div id = "l5"></div>
</div>

<div id = "first2">
    <div id = "r2"></div>
    <div id = "l2"></div>
</div>

</div>

<div id = "second">
  <div id = "secondplates">
    <div id = "r45b"></div>
    <div id = "l45b"></div>
  </div>

  <div id = "second35">
    <div id = "r35b"></div>
    <div id = "l35b"></div>
  </div>

  <div id = "second25">
    <div id = "r25b"></div>
    <div id = "l25b"></div>
  </div>

  <div id = "second10">
      <div id = "r10b"></div>
      <div id = "l10b"></div>
  </div>

  <div id = "second5">
      <div id = "r5b"></div>
      <div id = "l5b"></div>
  </div>

  <div id = "second2">
    <div id = "r2b"></div>
    <div id = "l2b"></div>
</div>
</div>

<div id = "third">
  <div id = "thirdplates">
    <div id = "r45c"></div>
    <div id = "l45c"></div>
  </div>

  <div id = "third35">
    <div id = "r35c"></div>
    <div id = "l35c"></div>
  </div>

  <div id = "third25">
    <div id = "r25c"></div>
    <div id = "l25c"></div>
  </div>

  <div id = "third10">
    <div id = "r10c"></div>
    <div id = "l10c"></div>
</div>

  <div id = "third5">
      <div id = "r5c"></div>
      <div id = "l5c"></div>
  </div>

  <div id = "third2">
    <div id = "r2c"></div>
    <div id = "l2c"></div>
</div>

</div>

<div id = "fourth">
    <div id = "fourthplates">
    <div id = "r45d"></div>
    <div id = "l45d"></div>
  </div>


  <div id = "fourth35">
    <div id = "r35d"></div>
    <div id = "l35d"></div>
  </div>

  <div id = "fourth25">
    <div id = "r25d"></div>
    <div id = "l25d"></div>
  </div>

<div id = "fourth10">
    <div id = "r10d"></div>
    <div id = "l10d"></div>
</div>

  <div id = "fourth5">
      <div id = "r5d"></div>
      <div id = "l5d"></div>
  </div>

  <div id = "fourth2">
    <div id = "r2d"></div>
    <div id = "l2d"></div>
</div>
</div>

<div id = "fifth">
  <div id = "fifthplates">
    <div id = "r45e"></div>
    <div id = "l45e"></div>
</div>

  <div id = "fifth35">
    <div id = "r35e"></div>
    <div id = "l35e"></div>
</div>

<div id = "fifth25">
    <div id = "r25e"></div>
    <div id = "l25"></div>
</div>

<div id = "fifth10">
    <div id = "r10e"></div>
    <div id = "l10e"></div>
</div>

<div id = "fifth5">
    <div id = "r5e"></div>
    <div id = "l5e"></div>
</div>

<div id = "fifth2">
    <div id = "r2e"></div>
    <div id = "l2e"></div>
</div>
</div>

</div>

  <br/>

      <button type = "button" id = "deload" class="btn btn-danger">Deload</button>
<br/><br/>
<br/>
<%= render 'form' %>

</div>
  

    
</body>
</html>

app/views/workouts/update.html.erb
<h1>Logs#update</h1>
<p>Find me in app/views/logs/update.html.erb</p>